# Generated by Django 3.2.4 on 2021-06-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210626_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
